"""empty message

Revision ID: 09982440804e
Revises: d3c73a155ccc
Create Date: 2021-09-15 15:02:28.038596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09982440804e'
down_revision = 'd3c73a155ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('token_exp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_exp')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
